name: Build Android APK (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install npm deps
        run: npm ci || npm install

      - name: Verify Capacitor CLI
        run: npx cap --version

      - name: Add Android platform
        run: npx cap add android

      - name: Sync web -> android
        run: npx cap sync android

      - name: Allow autoplay audio (no user gesture) - patch MainActivity
        run: |
          set -e
          MAIN_ACTIVITY=$(grep -Rsl "class MainActivity" android/app/src/main/java || true)
          if [ -n "$MAIN_ACTIVITY" ]; then
            if ! grep -q "setMediaPlaybackRequiresUserGesture(false)" "$MAIN_ACTIVITY"; then
              sed -i '1i import android.webkit.WebSettings;' "$MAIN_ACTIVITY"
              sed -i '/super.onCreate/s/$/\n    WebSettings ws = getBridge().getWebView().getSettings();\n    ws.setMediaPlaybackRequiresUserGesture(false);/' "$MAIN_ACTIVITY"
            fi
          fi
          exit 0

      - name: Build debug APK
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
